# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Madison Bai"                                # Your name
  description: "Professional Science Master's in Ecosystem Science and Sustainability"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: github
        href: https://github.com/madbai
      - icon: linkedin
        href: https://www.linkedin.com/in/madisonbai/
      - icon: envelope
        aria-label: email
        href: "mailto:madison.e.bai@colostate.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Madison Bai </span>
   
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true